name: Compile Typst and Release
on:
  push:
    branches:
      - main  # Runs every time you push to main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create the release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v3

      - name: Compile PDF
        run: typst compile main.typ namecards.pdf

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: namecards.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}